server:
  port: 9090

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 200313
    url: jdbc:mysql://localhost:3306/film_comment_system?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# 配置mybatis实体和xml映射
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# 配置mybatis实体和xml映射
mybatis-plus:
  #指定myBatis的核心配置文件与Mapper映射文件
  mapper-locations: classpath:mapper/*.xml
  # 别名，注意：对应实体类的路径
  type-aliases-package: com.wyl.pojo
#  global-config:
#    db-config:
#      table-prefix: ms_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

## 配置 Redis


redis:
  host: localhost
  port: 6379            # Redis 端口
  password: "" # 如果有密码可以在这里配置
  lettuce:
  pool:
  max-active: 100    # 最大并发连接数
  max-idle: 50       # 最大空闲连接数
  min-idle: 10       # 最小空闲连接数

# 文件上传的前缀url
fileBaseUrl: http://localhost:9090